version: "2.1"

services:
  spark-master:
    image: chetansurwade/spark-master:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    networks:
      - spark-net
  spark-worker:
    image: chetansurwade/spark-worker:latest
    container_name: spark-worker
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    depends_on:
      - spark-master
    networks:
      - spark-net
  zeppelin:
    # build: ./zeppelin
    image: chetansurwade/zeppelin:latest
    container_name: zeppelin
    ports:
      - "80:8080"
    volumes:
      - ./notebook:/zeppelin/notebook
      - ./logs:/zeppelin/logs
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "ZEPPELIN_ADDR=0.0.0.0"
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - spark-net
    
networks:
  spark-net:
    external:
      name: spark-net
